# 문서 업데이트는 언제하냐
# 아 키 괜히 날려먹어서
# 으아오너ㅏㄹ닝ㅁ러라이ㅏㅁ닝ㄹ
# 인생 쓰다 써
# 광대라도 좋아 난 바보가 된다해도 ~~
# Geeurneyyyyyyyyyyyyy
# 흨흨 가지마 '-'

# 얘는 이그노어 시키고 나중에 하자 너무 귀찮다
# 8개월만 시간 되돌리고 싶다
# 시간아 ~~~~~~~~~~~ 되돌아가라~~~~~~~~~
# 천벌 받는중인가 :(