-- 알림. 커뮤니티에서만 쓰는 것이 아니므로 어느 도메인에도 속하지 않는 테이블로 둔다.
-- 알림을 만드는 쪽이 recipient, type, target 을 넘기면 이 테이블에 쌓이고, 읽는 쪽은
-- 알림 종류를 몰라도 목록을 보여줄 수 있다.
CREATE TABLE IF NOT EXISTS notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id bigint NOT NULL REFERENCES users(id),
    -- 행동한 사람. 시스템이 보내는 알림에는 없다.
    actor_id bigint REFERENCES users(id),
    -- POST_LIKE, COMMENT, COMMENT_REPLY, COMMENT_LIKE, FOLLOW.
    -- 문자열로 두어 새 종류를 추가할 때 마이그레이션이 필요 없게 한다.
    type varchar(255) NOT NULL,
    -- 알림을 눌렀을 때 이동할 대상. 종류마다 가리키는 테이블이 달라
    -- reports 와 같은 이유로 외래키를 걸지 않는다.
    target_type varchar(255) NOT NULL,
    target_id bigint NOT NULL,
    -- 읽은 시각. 비어 있으면 읽지 않은 알림이다.
    read_at timestamp,
    created_at timestamp NOT NULL
);

-- 알림 목록은 항상 "내 알림을 최신순으로"라서 두 컬럼을 함께 잡는다.
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_id
    ON notifications (recipient_id, id DESC);

-- 안 읽은 개수는 화면을 열 때마다 조회한다. 읽은 알림이 쌓여도 비용이 늘지 않도록
-- 읽지 않은 행만 담는 부분 인덱스를 쓴다.
CREATE INDEX IF NOT EXISTS idx_notifications_unread
    ON notifications (recipient_id)
    WHERE read_at IS NULL;
