CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname varchar(255) NOT NULL,
    profile_image_url text,
    created_at timestamp NOT NULL,
    deleted_at timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_nickname_active
    ON users (nickname)
    WHERE deleted_at IS NULL;
