CREATE TABLE IF NOT EXISTS posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    content text NOT NULL,
    like_count integer NOT NULL DEFAULT 0,
    comment_count integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    deleted_at timestamp
);

CREATE TABLE IF NOT EXISTS post_media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts(id),
    media_type varchar(255) NOT NULL,
    url text NOT NULL,
    sort_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS post_place_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts(id),
    place_id bigint NOT NULL REFERENCES places(id),
    latitude numeric(12, 8),
    longitude numeric(12, 8)
);

CREATE INDEX IF NOT EXISTS idx_post_media_post_id ON post_media (post_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts (created_at);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts (user_id);
CREATE INDEX IF NOT EXISTS idx_post_place_tags_post_id ON post_place_tags (post_id);
CREATE INDEX IF NOT EXISTS idx_post_place_tags_place_id ON post_place_tags (place_id);



