CREATE TABLE IF NOT EXISTS posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    content text NOT NULL,
    like_count integer NOT NULL DEFAULT 0,
    comment_count integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    deleted_at timestamp
);

CREATE TABLE IF NOT EXISTS post_media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts(id),
    media_type varchar(255) NOT NULL,
    url text NOT NULL,
    sort_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS post_place_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts(id),
    place_id bigint NOT NULL REFERENCES places(id),
    latitude numeric(12, 8),
    longitude numeric(12, 8)
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts(id),
    user_id bigint NOT NULL REFERENCES users(id),
    parent_id bigint REFERENCES comments(id),
    content text NOT NULL,
    like_count integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    deleted_at timestamp
);

CREATE TABLE IF NOT EXISTS post_likes (
    post_id bigint NOT NULL REFERENCES posts(id),
    user_id bigint NOT NULL REFERENCES users(id),
    created_at timestamp NOT NULL,
    PRIMARY KEY (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS comment_likes (
    comment_id bigint NOT NULL REFERENCES comments(id),
    user_id bigint NOT NULL REFERENCES users(id),
    created_at timestamp NOT NULL,
    PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE IF NOT EXISTS bookmarks (
    user_id bigint NOT NULL REFERENCES users(id),
    post_id bigint NOT NULL REFERENCES posts(id),
    created_at timestamp NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS follows (
    follower_id bigint NOT NULL REFERENCES users(id),
    following_id bigint NOT NULL REFERENCES users(id),
    created_at timestamp NOT NULL,
    PRIMARY KEY (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS blocks (
    blocker_id bigint NOT NULL REFERENCES users(id),
    blocked_id bigint NOT NULL REFERENCES users(id),
    created_at timestamp NOT NULL,
    PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE IF NOT EXISTS hashtags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    post_count integer NOT NULL DEFAULT 0,
    CONSTRAINT uk_hashtags_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS post_hashtags (
    post_id bigint NOT NULL REFERENCES posts(id),
    hashtag_id bigint NOT NULL REFERENCES hashtags(id),
    PRIMARY KEY (post_id, hashtag_id)
);

CREATE TABLE IF NOT EXISTS reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id bigint NOT NULL REFERENCES users(id),
    target_type varchar(255) NOT NULL,
    target_id bigint NOT NULL,
    reason text NOT NULL,
    status varchar(255) NOT NULL,
    created_at timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_post_media_post_id ON post_media (post_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts (created_at);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts (user_id);
CREATE INDEX IF NOT EXISTS idx_post_place_tags_post_id ON post_place_tags (post_id);
CREATE INDEX IF NOT EXISTS idx_post_place_tags_place_id ON post_place_tags (place_id);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON comments (post_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments (parent_id);
CREATE INDEX IF NOT EXISTS idx_follows_following_id ON follows (following_id);
CREATE INDEX IF NOT EXISTS idx_post_hashtags_hashtag_id ON post_hashtags (hashtag_id);



